#! /usr/bin/env python
"""
    Copyright (C) 2015  Alexander Crosby

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""
import os
import requests

canonincal_url = "http://cfconventions.org/Data/cf-standard-names/%u/src/cf-standard-name-table.xml"
xmlname = "cf-standard-name-table.xml"

r = None
for i in range(29, 100, 1):
    r1 = requests.get(canonincal_url % (i,))
    if r1.status_code == 200:
        r = r1
    elif r is not None:
        break

xmlcontent = r.content
version = i - 1

current_path = os.path.join(os.path.split(os.path.abspath(__file__))[0], str(version))
if not os.path.exists(current_path):
    print "Getting Version %u" % (version,)
    os.mkdir(current_path)
    with open(os.path.join(current_path, xmlname), "w") as f:
        f.write(xmlcontent)
else:
    print "Already up-to-date: Version %u" % (version,)
